#ifndef __MCU_H_
#define __MCU_H_


#define DEVICE_STAUTS_NO_INIT  0x00
#define DEVICE_STAUTS_NO_START 0x01
#define DEVICE_STAUTS_STARTED  0x02




#define HSM_DEVICE_HARDWARE_SN 0x0000
///设备管理协议主命令
#define CMD_MAIN_SDF_ENV_MANAGE  0x00 ///环境管理类主命令（SDF接口）
#define CMD_MAIN_SDF_DEV_MANAGE  0x01 ///设备管理类主命令（SDF接口）
#define CMD_MAIN_SDF_RSA_MANAGE  0x02 ///RSA密钥管理类主命令（SDF接口）
#define CMD_MAIN_SDF_ECC_MANAGE  0x03 ///ECC密钥管理类主命令（SDF接口）
#define CMD_MAIN_SDF_KEK_MANAGE  0x04 ///KEK密钥管理类主命令（SDF接口）
#define CMD_MAIN_SDF_KEY_MANAGE  0x05 ///通用密钥管理类主命令（SDF接口）
#define CMD_MAIN_SDF_RSA_PROCESS  0x06 ///RSA运算类主命令（SDF接口）
#define CMD_MAIN_SDF_ECC_PROCESS  0x07 ///ECC运算类主命令（SDF接口）
#define CMD_MAIN_SDF_SYM_PROCESS  0x08 ///对称运算类主命令（SDF接口）
#define CMD_MAIN_SDF_HASH_PROCESS 0x09 ///杂凑运算类主命令（SDF接口）
#define CMD_MAIN_SDF_FILE_MANAGE  0x0a ///文件管理类主命令（SDF接口）
#define CMD_MAIN_SDF_EXT_MANAGE   0x10 ///扩展类主命令（SDF_EX接口）
#define CMD_MAIN_SMF_DEV_MANAGE   0xfd ///云密码机管理类主命令(SMF接口)


#define CMD_MAIN_SDF_EXT_MANAGE  0x10 ///SDF扩展接口
/**环境管理类**/
#define CMD_SUB_OPEN_DEVICE  0x01
#define CMD_SUB_CLOSE_DEVICE	 0x02
#define CMD_SUB_OPEN_SESSION  0x03
#define CMD_SUB_CLOSE_SESSION  0x04
#define CMD_SUB_OPEN_DEVICE_BY_ID  0x05
#define CMD_SUB_CLOSE_DEVICE_BY_ID  0x06
/**设备管理类**/
#define CMD_SUB_GET_DEVICE_INFO  0x01
#define CMD_SUB_GENERATE_RANDOM  0x02
#define CMD_SUB_GET_PRIVATEKEY_ACCESSRIGHT  0x03
#define CMD_SUB_RELEASE_PRIVATEKEY_ACCESSRIGHT  0x04
/**RSA密钥管理类**/
#define CMD_SUB_EXPORT_SIGNPUBLICKEY_RSA  0x01
#define CMD_SUB_EXPORT_ENCPUBLICKEY_RSA	 0x02
#define CMD_SUB_GENERATE_KEYPAIR_RSA  0x03
#define CMD_SUB_GENERATE_KEYWITHIPK_RSA  0x04
#define CMD_SUB_GENERATE_KEYWITHEPK_RSA  0x05
#define CMD_SUB_IMPORT_KEYWITHISK_RSA  0x06
#define CMD_SUB_EXCHANGE_DIGITENVELOPE_RSA  0x07
/**ECC密钥管理类**/
#define CMD_SUB_EXPORT_SIGNPUBLICKEY_ECC  0x01
#define CMD_SUB_EXPORT_ENCPUBLICKEY_ECC  0x02
#define CMD_SUB_GENERATE_KEYPAIR_ECC  0x03
#define CMD_SUB_GENERATE_KEYWITHIPK_ECC  0x04
#define CMD_SUB_GENERATE_KEYWITHEPK_ECC  0x05
#define CMD_SUB_IMPORT_KEYWITHISK_ECC  0x06
#define CMD_SUB_GENERATE_AGREEMENTDATA_ECC  0x07
#define CMD_SUB_GENERATE_SESSIONKEY_ECC  0x08
#define CMD_SUB_GENERATE_AGREEMENTDATAKEY_ECC  0x09
#define CMD_SUB_EXCHANGE_DIGITENVELOPE_ECC  0x10
/**KEK密钥管理类**/
#define CMD_SUB_GENERATE_KEY_KEK  0x01
#define CMD_SUB_IMPORT_KEY_KEK  0x02
/**通用密钥管理类**/
#define CMD_SUB_DESTROY_KEY  0x01

/**非对称算法运算类*/
#define CMD_SUB_SM2_INTERNAL_SIGN_ECC    0x01
#define CMD_SUB_SM2_INTERNAL_VERIFY_ECC  0x02
#define CMD_SUB_SM2_EXTERNAL_VERIFY_ECC  0x03
#define CMD_SUB_SM2_EXTERNAL_ENCRYPT_ECC 0x04

/* 杂凑运算类 */
#define CMD_SUB_SM3_HASH 		0x01
//#define CMD_SUB_SM3_HASH_INIT   0x02
//#define CMD_SUB_SM3_HASH_UPDATE 0x03
//#define CMD_SUB_SM3_HASH_FINAL  0x04
//#define CMD_SUB_SM3_HMAC		0x05
#define CMD_SUB_SM3_HMAC_INIT   0x06
#define CMD_SUB_SM3_HMAC_UPDATE 0x07
#define CMD_SUB_SM3_HMAC_FINAL  0x08


/* 对称算法运算类 */
#define CMD_SUB_SM4_ECB_ENC  0x01
#define CMD_SUB_SM4_ECB_DEC  0x02
#define CMD_SUB_SM4_CBC_ENC  0x03
#define CMD_SUB_SM4_CBC_DEC  0x04
#define CMD_SUB_SM4_OFB	     0x05
#define CMD_SUB_SM4_CFB  	 0x06
#define CMD_SUB_SM4_CTR  	 0x07
#define CMD_SUB_SM4_XTS  	 0x08
#define CMD_SUB_SM1_ECB_ENC  0x11
#define CMD_SUB_SM1_ECB_DEC  0x12
#define CMD_SUB_SM1_CBC_ENC  0x13
#define CMD_SUB_SM1_CBC_DEC  0x14
#define CMD_SUB_SM1_OFB	     0x15
#define CMD_SUB_SM1_CFB  	 0x16
#define CMD_SUB_SM1_CTR  	 0x17
#define CMD_SUB_SM1_XTS  	 0x18



/* 用户文件操作类 */
#define CMD_SUB_CREATE_FILE  0x01
#define CMD_SUB_READ_FILE    0x02
#define CMD_SUB_WRITE_FILE   0x03
#define CMD_SUB_DELETE_FILE  0x04

/**SDF扩展接口**/
#define CMD_SUB_IMPORT_PUBLICKEY_ECC        0x01/**导入临时公钥**/
#define CMD_SUB_IMPORT_KEY                  0x02/**导入临时对称密钥**/
#define CMD_SUB_GENERATE_KEY_HANDLE         0x03/**产生临时对称密钥**/
#define CMD_SUB_GENERATE_KEY_HANDLE_ECC     0x04/**产生临时非对称密钥**/
#define CMD_SUB_EXPORT_KEY_WITH_KEY         0x05/**使用临时对称密钥导出工作密钥**/
#define CMD_SUB_EXPORT_KEY_WITH_KEY_ECC     0x06/**使用临时公钥导出工作密钥**/


#define MCU_CMD_NULL 0x00
#define MCU_HARDWARE_PARAM_DEFAULT 0x0000
#define MCU_SOFTWARE_PARAM_DEFAULT 0x00000000


/* 设备管理类 */
#define MCU_CMD_GET_DEVICE_INFO 0x01
#define MCU_CMD_GENERATE_RANDOM 0x02
#define MCU_CMD_GET_PRIVATEKEY_ACCESSRIGHT 0x03
#define MCU_CMD_RELEASE_PRIVATEKEY_ACCESSRIGHT 0x04
#define MCU_CMD_INIT_DEVICE 0x05

/* 密钥管理类 */
#define MCU_CMD_EXPORT_SIGNPUBLICKEY_RSA 0x21
#define MCU_CMD_EXPORT_ENCPUBLICKEY_RSA	0x22
#define MCU_CMD_GENERATE_KEYPAIR_RSA 0x23
#define MCU_CMD_GENERATE_KEYWITHIPK_RSA 0x24
#define MCU_CMD_GENERATE_KEYWITHEPK_RSA 0x25
#define MCU_CMD_IMPORT_KEYWITHISK_RSA 0x26
#define MCU_CMD_EXCHANGE_DIGITENVELOPE_RSA 0x27
#define MCU_CMD_EXPORT_SIGNPUBLICKEY_ECC 0x28
#define MCU_CMD_EXPORT_ENCPUBLICKEY_ECC 0x29
#define MCU_CMD_GENERATE_KEYPAIR_ECC 0x2a
#define MCU_CMD_GENERATE_KEYWITHIPK_ECC 0x2b
#define MCU_CMD_GENERATE_KEYWITHEPK_ECC 0x2c
#define MCU_CMD_IMPORT_KEYWITHISK_ECC 0x2d
#define MCU_CMD_GENERATE_AGREEMENTDATA_ECC 0x2e
#define MCU_CMD_GENERATE_SESSIONKEY_ECC 0x2f
#define MCU_CMD_GENERATE_AGREEMENTDATAKEY_ECC 0x30
#define MCU_CMD_EXCHANGE_DIGITENVELOPE_ECC 0x31
#define MCU_CMD_GENERATE_KEY_KEK 0x32
#define MCU_CMD_IMPORT_KEY_KEK 0x33
#define MCU_CMD_DESTROY_KEY 0x34
#define MCU_CMD_EXPORT_DEVICE_KEY 0x35
#define MCU_CMD_GENERATE_KEY_EPK 0x36
#define MCU_CMD_IMPORT_KEY_EX2 0x37
#define MCU_CMD_IMPORT_KEY_PLAT 0x38
#define MCU_CMD_IMPORT_KEK_PLAIN 0x39
#define MCU_CMD_IMPORT_USERKEY_PLAIN 0x3A
#define MCU_CMD_IMPORT_KEYAGREMENT_PLAIN 0x3B
#define MCU_CMD_IMPORT_SELF_TEST_PLAIN 0x3C

/* 非对称算法运算类 */
#define MCU_CMD_EXTERNAL_PUBLICKEY_RSA          0x41
#define MCU_CMD_INTERNAL_PUBLICKEY_RSA          0x42
#define MCU_CMD_INTERNAL_PRIVATEKEY_RSA         0x43
#define MCU_CMD_EXTERNAL_VERIFY_ECC             0x44
#define MCU_CMD_INTERNAL_SIGN_ECC               0x45
#define MCU_CMD_INTERNAL_VERIFY_ECC             0x46
#define MCU_CMD_EXTERNAL_ENCRYPT_ECC            0x47
#define MCU_CMD_EXTERNAL_DECRYPT_ECC            0x48
#define MCU_CMD_INTERNAL_DECRYPT_ECC            0x49
#define MCU_CMD_EXTERNAL_PRIVATEKEY_RSA         0x4a
#define MCU_CMD_EXTERNAL_SIGN_ECC               0x4b
#define MCU_CMD_DECRYPT_PRIVATEKEY_EX2          0x4c
#define MCU_CMD_ENCRYPT_PRIVATEKEY_EX2          0x4d

/* 对称算法运算类 */
#define MCU_CMD_SM4                 0x61
#define MCU_CMD_SM4_MAC             0x62
#define MCU_CMD_SM4_EX              0x63

/* 杂凑运算类 */
#define MCU_CMD_HASH_INIT 0x81
#define MCU_CMD_HASH_UPDATE 0x82
#define MCU_CMD_HASH_FINAL 0x83


/*HMAC 运算类 */
#define MCU_CMD_HMAC_INIT 0x84
#define MCU_CMD_HMAC_UPDATE 0x85
#define MCU_CMD_HMAC_FINAL 0x86

/* 用户文件操作类 */
#define MCU_CMD_CREATE_FILE 0xa1
#define MCU_CMD_READ_FILE 0xa2
#define MCU_CMD_WRITE_FILE 0xa3
#define MCU_CMD_DELETE_FILE 0xa4

#define MCU_CMD_DEVICE_MANAGE 0xee
#define MCU_CMD_INVALID 0xff

#define MCU_STA_OK 0x00
#define MCU_STA_UNKNOWNERR 0x01
#define MCU_STA_NOTSUPPORT 0x02
#define MCU_STA_COMMFAIL 0x03
#define MCU_STA_HARDFAIL 0x04
#define MCU_STA_OPENDEVICE 0x05
#define MCU_STA_OPENSESSION 0x06
#define MCU_STA_PARDENY 0x07     //无私钥使用权限
#define MCU_STA_KEYNOTEXIST 0x08
#define MCU_STA_ALGNOTSUPPORT 0x09
#define MCU_STA_ALGMODNOTSUPPORT 0x0a
#define MCU_STA_PKOPERR 0x0b
#define MCU_STA_SKOPERR 0x0c
#define MCU_STA_SIGNERR 0x0d
#define MCU_STA_VERIFYERR 0x0e
#define MCU_STA_SYMOPERR 0x0f
#define MCU_STA_STEPERR 0x10
#define MCU_STA_FILESIZEERR 0x11
#define MCU_STA_FILENOEXIST 0x12
#define MCU_STA_FILEOFSERR 0x13
#define MCU_STA_KEYTYPEERR 0x14
#define MCU_STA_KEYERR 0x15


//添加不全的错误码
#define MCU_STA_ENCDATAERR   0x16 //ECC加密数据错误
#define MCU_STA_RANDERR	0x17 //随机数产生失败
#define MCU_STA_PRKRERR	0x18 //私钥使用权限获取失败
#define MCU_STA_MACERR 0x19 //MAC运算失败
#define MCU_STA_FILEEXSITS 0x1A //指定文件已存在
#define MCU_STA_FILEWERR 0x1B //文件写入失败
#define MCU_STA_NOBUFFER 0x1C //存储空间不足
#define MCU_STA_INARGERR 0x1D //输入参数错误
#define MCU_STA_OUTARGERR 0x1E //输出参数错误


#define MCU_STA_MAX 0xff


/*========对称密钥计算的子命令值=======*/
/*bits[7-7] :  密钥扩展（硬件API库填写）
				 0b  -  不做密钥扩展
				 1b  -  做密钥扩展
bits[6-3] : 保留
bits[2-0] : 工作模式（应用API库填写）
				 000b  -  ECB加密
				 001b  -  ECB解密
				 010b  -  CBC加密
				 011b  -  CBC解密
*/
#define SUB_CMD_ECB_ENC 0x00 //00000000
#define SUB_CMD_ECB_DEC 0x01
#define SUB_CMD_CBC_ENC 0x02
#define SUB_CMD_CBC_DEC 0x03

#define SUB_CMD_ECB_ENC_EX 0x80 //10000000
#define SUB_CMD_ECB_DEC_EX 0x81
#define SUB_CMD_CBC_ENC_EX 0x82
#define SUB_CMD_CBC_DEC_EX 0x83

/*===============管理工具子命令==================*/
#define SUB_CMD_MANAGER_BASE_ADDR (0x88020000)
#define SUB_CMD_MANAGER_OPEN_DEVICE (SUB_CMD_MANAGER_BASE_ADDR+0x01)
#define SUB_CMD_MANAGER_VERIFY 		(SUB_CMD_MANAGER_BASE_ADDR+0x02)
#define SUB_CMD_MANAGER_CLOSE_DEVICE (SUB_CMD_MANAGER_BASE_ADDR+0x03)
//#define SUB_CMD_MANAGER_ (SUB_CMD_MANAGER_BASE_ADDR+0x04)
#define SUB_CMD_MANAGER_DEVICE_INIT (SUB_CMD_MANAGER_BASE_ADDR+0x05)
#define SUB_CMD_MANAGER_REGISTER_NONMANAGER (SUB_CMD_MANAGER_BASE_ADDR+0x06)
//#define SUB_CMD_MANAGER_ (SUB_CMD_MANAGER_BASE_ADDR+0x07)
#define SUB_CMD_MANAGER_GENERATE_KEY (SUB_CMD_MANAGER_BASE_ADDR+0x08)
#define SUB_CMD_MANAGER_DESTROY_KEY (SUB_CMD_MANAGER_BASE_ADDR+0x09)
#define SUB_CMD_MANAGER_EXPORT_KEY (SUB_CMD_MANAGER_BASE_ADDR+0x10)
#define SUB_CMD_MANAGER_IMPORT_KEY (SUB_CMD_MANAGER_BASE_ADDR+0x11)
#define SUB_CMD_MANAGER_INSQURY_KEY (SUB_CMD_MANAGER_BASE_ADDR+0x12)
//#define SUB_CMD_MANAGER_ (SUB_CMD_MANAGER_BASE_ADDR+0x13)
//#define SUB_CMD_MANAGER_ (SUB_CMD_MANAGER_BASE_ADDR+0x14)
#define SUB_CMD_MANAGER_REGISTER_MANAGER (SUB_CMD_MANAGER_BASE_ADDR+0x15)
#define SUB_CMD_MANAGER_VERIFY_READ_WRITE (SUB_CMD_MANAGER_BASE_ADDR+0x16)
#define SUB_CMD_MANAGER_EXPORT_LOG (SUB_CMD_MANAGER_BASE_ADDR+0x17)
//#define SUB_CMD_MANAGER_ (SUB_CMD_MANAGER_BASE_ADDR+0x18)
//#define SUB_CMD_MANAGER_ (SUB_CMD_MANAGER_BASE_ADDR+0x19)
#define SUB_CMD_MANAGER_INSQURY_KEY_ISEXIST (SUB_CMD_MANAGER_BASE_ADDR+0x23)
#define SUB_CMD_MANAGER_MODIFY_PRICODE (SUB_CMD_MANAGER_BASE_ADDR+0x24)
#define SUB_CMD_MANAGER_MODIFY_USERPIN (SUB_CMD_MANAGER_BASE_ADDR+0x25)
#define SUB_CMD_MANAGER_INSQURY_DEL_USER (SUB_CMD_MANAGER_BASE_ADDR+0x26)

#define SUB_CMD_MANAGER_EXPORTPRIKEY	     (SUB_CMD_MANAGER_BASE_ADDR+0x30)
#define SUB_CMD_MANAGER_IMPORTPRIKEY	     (SUB_CMD_MANAGER_BASE_ADDR+0x31)
#define SUB_CMD_MANAGER_PUBKEYENCSYNKEY	     (SUB_CMD_MANAGER_BASE_ADDR+0x32)
#define SUB_CMD_MANAGER_PRIKEYDECSYNKEY	     (SUB_CMD_MANAGER_BASE_ADDR+0x33)
#define SUB_CMD_MANAGER_REBOOTDEVICE  	     (SUB_CMD_MANAGER_BASE_ADDR+0x34)





enum cmd_sub_cloud_manage_class {
	CMD_SUB_INIT_HSM_DEVICE = 0x01,
	CMD_SUB_CREATE_INIT_VSM_DEVICE = 0x02,
	CMD_SUB_START_DEVICE = 0x03,
	CMD_SUB_GET_DEVICE_STATUS = 0x04,
	CMD_SUB_CLOSET_DEVICE = 0x05,
	CMD_SUB_IMPORT_CERT = 0x06,
	CMD_SUB_ADD_USER = 0x07,
	CMD_SUB_DELETE_USER = 0x08,
	CMD_SUB_GENERATE_SYM_KEY = 0x09,
	CMD_SUB_GENERATE_ALL_SYM_KEY = 0x0a,
	CMD_SUB_GENERATE_ECC_KEY = 0x0b,
	CMD_SUB_GENERATE_ALL_ECC_KEY = 0x0c,
	CMD_SUB_GENERATE_RSA_KEY = 0x0d,
	CMD_SUB_GENERATE_ALL_RSA_KEY = 0x0e,
	CMD_SUB_DELETE_SYM_KEY = 0x0f,
	CMD_SUB_DELETE_ECC_KEY = 0x10,
	CMD_SUB_DELETE_RSA_KEY = 0x11,
	CMD_SUB_GET_KEY_COUNT = 0x12,
	CMD_SUB_GET_KEK_ADDRESS = 0x13,
	CMD_SUB_GET_ECC_KEY_ADDRESS = 0x14,
	CMD_SUB_CHANGE_ECC_KEY_ACCESSCODE = 0x15,
	CMD_SUB_GET_DEVICE_CERT = 0x16,
	CMD_SUB_GET_SYSTEM_CERT = 0x17,
	CMD_SUB_BACKUP_USER_KEY = 0x18,
	CMD_SUB_RESTORE_USER_KEY = 0x19,
	CMD_SUB_BACKUP_VSM = 0x1a,
	CMD_SUB_RESTORE_VSM = 0x1b,
	CMD_SUB_IMPORT_KMC_PUB_KEY = 0x1c,
};


// typedef struct MCU_KEY_ADDRESS
// {
// 	u32 keyCount;       ///密钥数量
// 	u32 beginAddress;   ///内存首地址
// }sis_mcu_key_address;

#define MCU_KEY_TYPE_SIGN_PUB 0x01
#define MCU_KEY_TYPE_SIGN_PRV 0x02
#define MCU_KEY_TYPE_ENC_PUB  0x03
#define MCU_KEY_TYPE_ENC_PRV  0x04

#define MCU_MEM_BOLK_SIZE_ECC 192   //签名64+32 加密64+32
#define MCU_MEM_BOLK_SIZE_KEK 16

#endif // MCU_H_INCLUDED

